# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [2]:
# Exercise 1
import numpy as np
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [3]:
# Exercise 2
arr_z = np.zeros((3,3))
print(arr_z)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [4]:
# Exercise 3
x = np.linspace(0,5,10).astype(int)
print(x)

[0 0 1 1 2 2 3 3 4 5]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [5]:
# Exercise 4
y = np.identity(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [6]:
# Exercise 5
rand = np.random.randint(1,size = (4,4))
rand

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])


---

### Exercise 6:
Find the shape of a NumPy array.


In [7]:
# Exercise 6
arr.shape

(10,)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [8]:
# Exercise 7
arr_ = np.arange(0,16).reshape((4,4))
arr_

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [9]:
# Exercise 8
arr_.dtype

dtype('int32')


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [158]:
# Exercise 9
arr = np.arange(1, 101)
even_numbers = arr[arr % 2 == 0]

print("Even numbers from 1 to 100:")
print(even_numbers)


Even numbers from 1 to 100:
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [11]:
# Exercise 10
a = np.random.randint(10,50,size = (6,6))
a

array([[13, 24, 22, 19, 37, 41],
       [21, 25, 38, 37, 28, 14],
       [17, 27, 44, 28, 25, 33],
       [33, 48, 33, 11, 28, 22],
       [12, 48, 35, 12, 49, 12],
       [16, 40, 34, 49, 40, 22]])


---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [12]:
# Exercise 11


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [78]:
# Exercise 12
m = np.arange(6).reshape((2,3))
n = np.arange(1,7).reshape((2,3))
sum = np.add(m,n)
sum

array([[ 1,  3,  5],
       [ 7,  9, 11]])


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [82]:
# Exercise 13
mn = np.mean(m)
md = np.median(m)
std = np.std(m)
print(f"mean:{mn}, median:{md}, standard deviation: {std}")

mean:2.5, median:2.5, standard deviation: 1.707825127659933



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [84]:
# Exercise 14
mini = np.min(m)
maxi = np.max(m)
print(f"minimum:{mini}, maximum:{maxi}")

minimum:0, maximum:5



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [89]:
# Exercise 15
value = np.random.randint(1,100,20)
max_index = np.argmax(value)
print(value)
max_index

[67 44 52 75 13 59 63  6 84 83 19 79 65 12 72 85 12 25 81 13]


15


---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [95]:
# Exercise 16
# my_array = np.array([1, 2, 3, 4, 5])
reverse_value = value[::-1]
reverse_value

array([13, 81, 25, 12, 85, 72, 12, 65, 79, 19, 83, 84,  6, 63, 59, 13, 75,
       52, 44, 67])


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [98]:
# Exercise 17
matrix1 = np.arange(1,10).reshape((3,3))
matrix2 = np.arange(11,20).reshape((3,3))
result_matrix = np.multiply(matrix1, matrix2)
print(matrix1)
print(matrix2)
print(result_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [100]:
# Exercise 18
matri = np.array([1,2,3,4,5,6,7])
d_matri = np.diag(matri)
d_matri

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [101]:
# Exercise 19
matrix3 = np.array([[1,2,3],[4,5,6]])
matrix4 = np.array([[7,8,9],[10,11,12]])
resultmatrix = np.multiply(matrix1, matrix2)
print(matrix3)
print(matrix4)
print(resultmatrix)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [102]:
# Exercise 20
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = arr_2d.flatten()
print(arr_1d) 

[1 2 3 4 5 6]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [103]:
# Exercise 21
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.vstack((array1, array2))
print(result)

[[1 2 3]
 [4 5 6]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [104]:
# Exercise 22
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_ = np.hstack((array1, array2))
print(result_)

[1 2 3 4 5 6]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [107]:
# Exercise 23
arr = np.array([1, 2, 3, 4, 5, 6, 7,8])
sub_arrays = np.array_split(arr, 4) 
print(sub_arrays)
  

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [111]:
# Exercise 24
random_array = np.random.rand(3, 4)
rounded_array = np.round(random_array, 2)
print(rounded_array)

[[0.29 0.79 0.58 0.85]
 [0.42 0.07 0.89 0.9 ]
 [0.67 0.49 0.68 0.41]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [112]:
# Exercise 25
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(arr)
print(unique_elements) 

[1 2 3 4 5]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [115]:
# Exercise 26
new_arr = np.array([1, 5, 2, 8, -3, 10, 0])
new_arr[new_arr < 3] = 3
new_arr

array([ 3,  5,  3,  8,  3, 10,  3])


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [116]:
# Exercise 27
arr = np.array([1, 2, 3, 4, 5])
cumulative_sum_arr = np.cumsum(arr)
print(cumulative_sum_arr) 

[ 1  3  6 10 15]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [119]:
# Exercise 28
arr = np.array([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
non_zero = np.count_nonzero(arr)
print(arr)
print("\nNumber of non-zero elements:", non_zero)

[[1 0 2]
 [0 3 0]
 [4 0 5]]

Number of non-zero elements: 5



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [120]:
# Exercise 29
random_array = np.random.randint(0, 100, size=10)
sorted_array = np.sort(random_array)
print("Original Array:", random_array)
print("Sorted Array:", sorted_array)

Original Array: [67 69 83 45  8 68 73 22 28 85]
Sorted Array: [ 8 22 28 45 67 68 69 73 83 85]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [121]:
# Exercise 30
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)

print("Original Matrix:")
print(matrix)
print("\nRow-wise Sum:", row_sums)
print("Column-wise Sum:", col_sums)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row-wise Sum: [ 6 15 24]
Column-wise Sum: [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [122]:
# Exercise 31
random_array = np.random.rand(5, 5)

min_val = np.min(random_array)
max_val = np.max(random_array)

normalized_array = (random_array - min_val) / (max_val - min_val)

print("Original Array:")
print(random_array)
print("\nNormalized Array:")
print(normalized_array)

Original Array:
[[0.77423217 0.58435966 0.92063663 0.07186837 0.69111312]
 [0.37348545 0.72140236 0.16565227 0.86540287 0.64865649]
 [0.88876243 0.16022985 0.0769431  0.17361313 0.52483069]
 [0.3562722  0.9049972  0.29164755 0.94733675 0.3190188 ]
 [0.06717012 0.42232425 0.39983375 0.60520517 0.94588374]]

Normalized Array:
[[0.80332749 0.58760413 0.9696647  0.00533791 0.70889192]
 [0.34801971 0.74330498 0.11189036 0.90691095 0.66065487]
 [0.93345088 0.10572967 0.01110356 0.12093507 0.51997037]
 [0.3284629  0.95189599 0.2550397  1.         0.28613751]
 [0.         0.40350783 0.37795529 0.61128772 0.99834917]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [125]:
# Exercise 32
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

dot_product = np.dot(array1, array2)
print(dot_product)

32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [126]:
# Exercise 33
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

trace = np.trace(matrix)
print(trace) 

15



---

### Exercise 34:
Create a 2D array and swap two rows.


In [127]:
# Exercise 34
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:")
print(arr)
arr[[0, 2]] = arr[[2, 0]]
print("\nArray after swapping row 0 and row 2:")
print(arr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping row 0 and row 2:
[[7 8 9]
 [4 5 6]
 [1 2 3]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [129]:
# Exercise 35
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)

col_vector = arr_1d.reshape(-1, 1)
print("\nColumn Vector:")
print(col_vector)

1D Array:
[1 2 3 4 5]

Column Vector:
[[1]
 [2]
 [3]
 [4]
 [5]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [130]:
# Exercise 36
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

determinant = np.linalg.det(matrix)
print(f"The determinant of the matrix is: {determinant}")

The determinant of the matrix is: 0.0



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [131]:
# Exercise 37
A = np.array([[4, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [133]:
# Exercise 38
A = np.array([[2, 4], [6, 8]])
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print(x)

[-2.    2.25]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [134]:
# Exercise 39
original_array = np.array([1, 2, 3, 4, 5])
mean = 0
std_dev = 1
noise = np.random.normal(mean, std_dev, size=original_array.shape)
noisy_array = original_array + noise

print("Original array:", original_array)
print("Noisy array:", noisy_array)

Original array: [1 2 3 4 5]
Noisy array: [2.22983823 0.8813357  3.41361732 3.17072678 5.88201668]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [135]:
# Exercise 40
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

diagonal_elements = np.diag(matrix)

print("Matrix:")
print(matrix)
print("\nDiagonal elements:")
print(diagonal_elements)

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal elements:
[ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [136]:
# Exercise 41
random_array = np.random.rand(100)
scaled_array = random_array * 40 + 10

clipped_array = np.clip(scaled_array, 10, 50)
print(clipped_array)

[29.65394249 20.54703137 27.81700749 24.78627202 15.69622608 39.65093533
 16.01082025 13.76275821 20.02429892 36.92386767 29.34007763 31.85555038
 34.93461518 18.12868707 26.42951231 46.00851516 19.06971438 10.86902729
 20.24838759 16.78143839 15.23374472 32.75712638 40.89543857 41.57739043
 19.73880476 37.05304799 37.80547412 20.88588451 17.78683026 13.75067878
 18.16847599 39.53672761 26.9419665  49.70731283 12.06092597 31.64861467
 15.51341382 46.54550621 34.09986125 37.92087798 28.23770729 26.31365245
 42.74913719 33.19031747 40.52356587 37.23211113 49.43533647 31.52437397
 45.50405439 13.18940738 12.51252242 27.3266862  27.29211313 22.21804547
 40.081181   12.02916187 42.93908827 48.42555218 33.24571565 40.90032396
 11.44300681 33.94351512 46.96678902 26.61356473 20.89702167 27.35005723
 44.14640057 38.3054157  18.50499316 18.9482964  44.91601127 20.54989127
 32.3237795  13.81603174 46.96140905 38.26129331 35.31888599 44.77206111
 40.89608719 12.66106072 29.57344339 48.14437601 28


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [137]:
# Exercise 42
my_array = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])
my_array[my_array < 0] = 0

print(my_array)

[[1 0 3]
 [0 5 0]
 [7 0 9]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [139]:
# Exercise 43
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

inner_product = np.inner(a, b)
print(inner_product) 
outer_product = np.outer(a, b)
print(outer_product)

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [141]:
# Exercise 44
from scipy.spatial.distance import pdist, squareform
points = np.random.rand(4, 2)
dists = squareform(pdist(points))
dists

array([[0.        , 0.67490273, 0.40943727, 0.7957396 ],
       [0.67490273, 0.        , 0.63612977, 0.9577896 ],
       [0.40943727, 0.63612977, 0.        , 0.41094904],
       [0.7957396 , 0.9577896 , 0.41094904, 0.        ]])


---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [142]:
# Exercise 45
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('height', 'f8')])
data = np.array([('Alice', 25, 1.65), ('Bob', 30, 1.80), ('Charlie', 28, 1.75)], dtype=dt)

print(data)

[('Alice', 25, 1.65) ('Bob', 30, 1.8 ) ('Charlie', 28, 1.75)]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [143]:
# Exercise 46
matrix = np.random.randint(0, 10, size=(5, 5))
unique_values, counts = np.unique(matrix, return_counts=True)
print("Matrix:\n", matrix)
print("\nUnique values and their counts:")
for value, count in zip(unique_values, counts):
    print(f"{value}: {count}")

Matrix:
 [[9 6 1 2 2]
 [8 5 2 0 4]
 [1 1 1 6 8]
 [6 2 7 0 9]
 [3 7 2 5 4]]

Unique values and their counts:
0: 2
1: 4
2: 5
3: 1
4: 2
5: 2
6: 3
7: 2
8: 2
9: 2



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [144]:
# Exercise 47
arr = np.random.rand(3, 3)
row_means = np.mean(arr, axis=1, keepdims=True)
result = arr - row_means

print("Original array:\n", arr)
print("\nArray with row means subtracted:\n", result)

Original array:
 [[0.66337115 0.41298312 0.88985223]
 [0.8137614  0.60020993 0.6069025 ]
 [0.60962643 0.33107574 0.08298839]]

Array with row means subtracted:
 [[ 0.00796899 -0.24241905  0.23445006]
 [ 0.14013679 -0.07341468 -0.06672211]
 [ 0.26839624 -0.01015445 -0.2582418 ]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [145]:
# Exercise 48
random_array = np.random.randint(0, 101, 100)
any_greater_than_50 = np.any(random_array > 50)

print("Random Array:", random_array)
print("Any values greater than 50:", any_greater_than_50)

Random Array: [90 59 93 32 74 35 13 47 22 75 58 82 52 35 27 55 61 95 54 33 57 81 96  8
 26 21 74 71 70 54 75 47 19 74 44 23  0 18 14 94 93  6 93 43 15 86 84 74
 37 26 79 73 83 81 43 88 31 22 90 72 65 12 74 24 63 69 49 27 89 90 41 77
  4  9 48 38 99 14 50 58 21 16 76  4 65 61 69 19 39 85 61 23 10 73  4 15
 52 32 94 65]
Any values greater than 50: True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [146]:
# Exercise 49
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
window_size = 3
weights = np.ones(window_size) / window_size
moving_avg = np.convolve(data, weights, mode='valid')

print("Moving average:")
print(moving_avg)


Moving average:
[2. 3. 4. 5. 6. 7. 8.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [147]:
# Exercise 50
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 4, 5, 4, 5])

correlation_matrix = np.corrcoef(array1, array2)
pearson_coefficient = correlation_matrix[0, 1]

print(pearson_coefficient)

0.7745966692414834



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [148]:
# Exercise 51
radians = np.array([0, np.pi/6, np.pi/4, np.pi/2, np.pi])
degrees = np.degrees(radians)

print("Degrees:")
print(degrees)


Degrees:
[  0.  30.  45.  90. 180.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [152]:
# Exercise 52
arr = np.random.randint(10, size = (5))
variance = np.var(arr)
std_dev = np.std(arr)

print("Array:", arr)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Array: [0 4 8 0 2]
Variance: 8.959999999999999
Standard Deviation: 2.993325909419153



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [153]:
# Exercise 53
arr = np.array([
    [1, 7, 3, 4],
    [8, 2, 5, 1],
    [6, 9, 0, 3]
])
max_indices_col = np.argmax(arr, axis=0)
max_indices_row = np.argmax(arr, axis=1)

print("Array:")
print(arr)

print("\nIndices of max values along columns (axis=0):", max_indices_col)
print("Indices of max values along rows (axis=1):", max_indices_row)


Array:
[[1 7 3 4]
 [8 2 5 1]
 [6 9 0 3]]

Indices of max values along columns (axis=0): [1 2 1 0]
Indices of max values along rows (axis=1): [1 0 1]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [154]:
# Exercise 54
A = np.array([[4, 7],
              [2, 6]])

A_inv = np.linalg.inv(A)

print("Inverse of the matrix:")
print(A_inv)


Inverse of the matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [155]:
# Exercise 55
arr = np.random.rand(10)       
standardized = (arr - np.mean(arr)) / np.std(arr)

print("Original:", arr)
print("Standardized:", standardized)


Original: [0.55801301 0.68616638 0.42706411 0.13562096 0.40893662 0.06732834
 0.24851477 0.58435449 0.52749187 0.89745657]
Standardized: [ 0.43163585  0.96393471 -0.11227453 -1.32281509 -0.18756901 -1.60647586
 -0.85389845  0.54104806  0.30486301  1.84155131]



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [156]:
# Exercise 56
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b
subtraction = a - b

print("Addition:", addition)
print("Subtraction:", subtraction)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [58]:
# Exercise 57
arr = np.random.rand(10)
max_index = np.argmax(arr)

print("Array:", arr)
print("Index of max element:", max_index)



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [59]:
# Exercise 58
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

rotated = np.rot90(arr)

print("Original:")
print(arr)

print("\nRotated 90 degrees:")
print(rotated)



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [60]:
# Exercise 59
matrix = np.array([[1, 2],
                   [3, 4]])

fro_norm = np.linalg.norm(matrix, 'fro')

print("Frobenius norm:", fro_norm)



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [157]:
# Exercise 60
arr = np.random.randint(0, 10, size=(3, 4, 5))  
subarray = arr[0, 1:3, 2:5] 

print("Original shape:", arr.shape)
print("Sliced subarray:\n", subarray)


Original shape: (3, 4, 5)
Sliced subarray:
 [[0 5 4]
 [4 6 4]]



---